"""change unique constraint on categories name to per user

Revision ID: 5d943d568aa5
Revises: 9b0740d5db94
Create Date: 2025-12-01 18:04:15.276597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d943d568aa5'
down_revision: Union[str, None] = '9b0740d5db94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_unique_constraint('ix_categories_name_user_id', 'categories', ['name', 'user_id'])
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('expenses', 'credit')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'is_active')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_users_account_number', table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('ix_users_account_number', 'users', ['account_number'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('expenses', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('expenses', sa.Column('credit', mysql.FLOAT(), nullable=True))
    op.alter_column('expenses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('ix_categories_name_user_id', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    # ### end Alembic commands ###
